#!/bin/bash

export BASH_COMPLETION
export FZF_TMUX=1
eval "$(gdircolors ~/.dircolors)"

# Aliases
alias vim="nvim"
alias mutt="neomutt"
alias ls='gls --color=auto'
alias ll='ls -al'
alias docker-env='eval "$(docker-machine env)"'

BASH_COMPLETION="/usr/local/etc/bash_completion"

if [ -f $BASH_COMPLETION ]; then
  # shellcheck disable=SC1091
  # shellcheck source=/usr/local/etc/bash_completion
  source $BASH_COMPLETION
fi
