#!/bin/bash

export GIT_EDITOR
export BASH_COMPLETION
export FZF_TMUX=1
eval "$(gdircolors ~/.dircolors)"

# Aliases
alias mutt="neomutt"
alias nvimdiff="nvim -d"
alias ls='gls --color=auto'
alias ll='ls -al'
alias docker-env='eval "$(docker-machine env)"'
alias sed="LC_ALL=C sed"

GIT_EDITOR="nvim"
BASH_COMPLETION="/usr/local/etc/bash_completion"

if [ -f $BASH_COMPLETION ]; then
  # shellcheck disable=SC1091
  # shellcheck source=/usr/local/etc/bash_completion
  source $BASH_COMPLETION
fi

cert-info() {
 openssl x509 -text -noout -in "$1"
}

cert-host() {
 openssl s_client -showcerts -servername "$1" -connect "$1:443" </dev/null
}

kubectl-logs() {
 kubectl get pods | grep "$1" | awk '{print $1}' | xargs -I pod kubectl logs pod  -c "$1"
}
