#!/bin/bash

export BASH_COMPLETION
export FZF_TMUX=1
eval "$(gdircolors ~/.dircolors)"

# Aliases
alias vim="nvim"
alias mutt="neomutt"
alias ls='gls --color=auto'
alias ll='ls -al'
alias docker-env='eval "$(docker-machine env)"'
alias sed="LC_ALL=C sed"

BASH_COMPLETION="/usr/local/etc/bash_completion"

if [ -f $BASH_COMPLETION ]; then
  # shellcheck disable=SC1091
  # shellcheck source=/usr/local/etc/bash_completion
  source $BASH_COMPLETION
fi

git-release() {
   RELEASE_NAME=$1

   if [ -z "$RELEASE_NAME" ]; then
     RELEASE_NAME="release"
   else
     RELEASE_NAME="$RELEASE_NAME-release"
   fi

   git checkout -b "$RELEASE_NAME"-"$(date '+%Y-%m-%d')"
}
