#!/bin/bash

alias docker-env='eval "$(docker-machine env)"'

DOCKER_MACHINE_NAME="default"
DOCKER_MACHINE_STATUS=$(docker-machine ls | grep -i "$DOCKER_MACHINE_NAME" | grep "Running" | awk '{ print $2}')

if [[ "$DOCKER_MACHINE_STATUS" != "*" ]]; then
	if [ "$DOCKER_MACHINE_STATUS" == "-" ]; then
		eval "$(docker-machine env $DOCKER_MACHINE_NAME)"
	fi
fi
