#!/bin/bash

export PATH="$HOME/workspace/hippo/hippo-sdk/bin:$PATH"

hippo-env() {
  export AWS_PROFILE="hippo-$1"

  case "$1" in
    "prod")
      eval "$(hsdk setenv production)" ;;
    "network")
      eval "$(hsdk setenv hippo-network)" ;;
    *)
      eval "$(hsdk setenv "$1")" ;;
  esac
}

hippo-domain() {
  case "$1" in
    "network")
      echo "hippo.partners" ;;
    *)
      echo "hippo-$1.tools" ;;
  esac
}

hippo-ssh() {
  DOMAIN="$(hippo-domain "$1")"
  ssh "svetlin@jumpbox.$DOMAIN"
}

hippo-proxy() {
  DOMAIN="$(hippo-domain "$1")"
  ssh -o ServerAliveInterval=5 -o ServerAliveCountMax=1 -o ConnectTimeout=3 -L 5430:"$2.$DOMAIN:5432 svetlin@jumpbox.$DOMAIN"
}
