#!/bin/bash

export PATH="$HOME/workspace/hippo/hsdk/bin:$PATH"

alias hsdk-jump="hsdk jump svetlin"

hippo-env() {
 eval "$(hsdk setenv "$1")"

 if [ -n "$TMUX" ]; then
   tmux setenv -g HSDK_ENV_DESCRIPTION "$HSDK_ENV_ALIAS"
 fi
}
