#!/bin/bash

export NVM_DIR="$HOME/.nvm"
export YARN_BIN

# shellcheck disable=SC1091
source "/usr/local/opt/nvm/nvm.sh"

if which yarn >&-
then
  YARN_BIN="$(yarn global bin)"
  export PATH="${PATH}:${YARN_BIN}"
fi
