#!/bin/bash

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYTHON_BIN="$HOME/.pyenv/versions/neovim-python-3.6.3/bin"

eval "$(pyenv init - --no-rehash)"
eval "$(pyenv virtualenv-init - --no-rehash)"

alias aws='"$PYTHON_BIN"/aws'
alias powerline-shell='"$PYTHON_BIN"/powerline-shell'
