#!/bin/bash

MACHINE_NAME=${MACHINE_NAME:-snowflake}

sudo scutil --set HostName "$MACHINE_NAME"
sudo scutil --set LocalHostName "$MACHINE_NAME"
sudo scutil --set ComputerName "$MACHINE_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$MACHINE_NAME"
dscacheutil -flushcache
